definitions:
  handler.RegisterAnonymousResponse:
    properties:
      token:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: iamvkosarev@gmail.com
    name: API Support
  description: Server for Moscow hackathon game project.
  title: MosHackGame API
  version: "1.0"
paths:
  /user/token/anonymous:
    get:
      description: create new token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.RegisterAnonymousResponse'
      summary: Provide anonymouse user token
      tags:
      - user
swagger: "2.0"
